# Copyright 2018 Vinnie Falco
# Distributed under the Boost Software License, Version 1.0.
# (See accompanying file LICENSE_1_0.txt or copy at http://boost.org/LICENSE_1_0.txt)

sudo: true
language: cpp
compiler:
  - gcc
  - clang
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - llvm-toolchain-precise-3.9
    packages:
    - g++-7
    - clang-3.9
install:
- "[ $CXX = g++ ] && export CXX=g++-7 || true"
- "[ $CXX = clang++ ] && export CXX=clang++-3.9 || true"
script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
notifications:
  email:
    on_success: never
